create table `websockets_statistics_entries` (`id` int unsigned not null auto_increment primary key, `app_id` varchar(125) not null, `peak_connection_count` int not null, `websocket_message_count` int not null, `api_message_count` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(125) not null, `email` varchar(125) not null, `email_verified_at` timestamp null, `avatar` varchar(125) null, `password` varchar(125) not null, `remember_token` varchar(100) null, `last_seen` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `users` add unique `users_email_unique`(`email`);
create table `password_resets` (`email` varchar(125) not null, `token` varchar(125) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `password_resets` add index `password_resets_email_index`(`email`);
create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(125) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `failed_jobs` add unique `failed_jobs_uuid_unique`(`uuid`);
create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(125) not null, `tokenable_id` bigint unsigned not null, `name` varchar(125) not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `personal_access_tokens` add index `personal_access_tokens_tokenable_type_tokenable_id_index`(`tokenable_type`, `tokenable_id`);
alter table `personal_access_tokens` add unique `personal_access_tokens_token_unique`(`token`);
create table `courses` (`id` bigint unsigned not null auto_increment primary key, `title` varchar(200) not null, `active` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null, `teacher_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `courses` add constraint `courses_teacher_id_foreign` foreign key (`teacher_id`) references `users` (`id`) on delete cascade;
create table `quizzes` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(125) not null, `created_at` timestamp null, `updated_at` timestamp null, `start_date` datetime not null, `duration` int not null, `description` text null, `course_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `quizzes` add constraint `quizzes_course_id_foreign` foreign key (`course_id`) references `courses` (`id`) on delete cascade;
create table `quiz_questions` (`id` bigint unsigned not null auto_increment primary key, `question` varchar(125) not null, `order` tinyint unsigned not null, `quiz_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `quiz_questions` add constraint `quiz_questions_quiz_id_foreign` foreign key (`quiz_id`) references `quizzes` (`id`) on delete cascade;
create table `quiz_answers` (`id` bigint unsigned not null auto_increment primary key, `answer` varchar(125) not null, `right_answer` tinyint(1) not null, `created_at` timestamp null, `updated_at` timestamp null, `question_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `quiz_answers` add constraint `quiz_answers_question_id_foreign` foreign key (`question_id`) references `quiz_questions` (`id`) on delete cascade;
create table `course_students` (`course_id` bigint unsigned not null, `student_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `course_students` add constraint `course_students_course_id_foreign` foreign key (`course_id`) references `courses` (`id`) on delete cascade;
alter table `course_students` add constraint `course_students_student_id_foreign` foreign key (`student_id`) references `users` (`id`) on delete cascade;
alter table `course_students` add primary key `course_students_course_id_student_id_primary`(`course_id`, `student_id`);
alter table `course_students` add index `course_students_course_id_index`(`course_id`);
alter table `course_students` add index `course_students_student_id_index`(`student_id`);
create table `quiz_students` (`id` bigint unsigned not null auto_increment primary key, `quiz_id` bigint unsigned not null, `student_id` bigint unsigned not null, `submitted` tinyint(1) not null default '0', `submitted_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `quiz_students` add constraint `quiz_students_quiz_id_foreign` foreign key (`quiz_id`) references `quizzes` (`id`) on delete cascade;
alter table `quiz_students` add constraint `quiz_students_student_id_foreign` foreign key (`student_id`) references `users` (`id`) on delete cascade;
alter table `quiz_students` add index `quiz_students_quiz_id_index`(`quiz_id`);
alter table `quiz_students` add index `quiz_students_student_id_index`(`student_id`);
create table `permissions` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(125) not null, `guard_name` varchar(125) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `permissions` add unique `permissions_name_guard_name_unique`(`name`, `guard_name`);
create table `roles` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(125) not null, `guard_name` varchar(125) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `roles` add unique `roles_name_guard_name_unique`(`name`, `guard_name`);
create table `model_has_permissions` (`permission_id` bigint unsigned not null, `model_type` varchar(125) not null, `model_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `model_has_permissions` add index `model_has_permissions_model_id_model_type_index`(`model_id`, `model_type`);
alter table `model_has_permissions` add constraint `model_has_permissions_permission_id_foreign` foreign key (`permission_id`) references `permissions` (`id`) on delete cascade;
alter table `model_has_permissions` add primary key `model_has_permissions_permission_model_type_primary`(`permission_id`, `model_id`, `model_type`);
create table `model_has_roles` (`role_id` bigint unsigned not null, `model_type` varchar(125) not null, `model_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `model_has_roles` add index `model_has_roles_model_id_model_type_index`(`model_id`, `model_type`);
alter table `model_has_roles` add constraint `model_has_roles_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete cascade;
alter table `model_has_roles` add primary key `model_has_roles_role_model_type_primary`(`role_id`, `model_id`, `model_type`);
create table `role_has_permissions` (`permission_id` bigint unsigned not null, `role_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `role_has_permissions` add constraint `role_has_permissions_permission_id_foreign` foreign key (`permission_id`) references `permissions` (`id`) on delete cascade;
alter table `role_has_permissions` add constraint `role_has_permissions_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete cascade;
alter table `role_has_permissions` add primary key `role_has_permissions_permission_id_role_id_primary`(`permission_id`, `role_id`);
create table `activity_log` (`id` bigint unsigned not null auto_increment primary key, `log_name` varchar(125) null, `description` text not null, `subject_type` varchar(125) null, `subject_id` bigint unsigned null, `causer_type` varchar(125) null, `causer_id` bigint unsigned null, `properties` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `activity_log` add index `subject`(`subject_type`, `subject_id`);
alter table `activity_log` add index `causer`(`causer_type`, `causer_id`);
alter table `activity_log` add index `activity_log_log_name_index`(`log_name`);
alter table `activity_log` add `event` varchar(125) null after `subject_type`;
alter table `activity_log` add `batch_uuid` char(36) null after `properties`;
create table `notifications` (`id` char(36) not null, `type` varchar(125) not null, `notifiable_type` varchar(125) not null, `notifiable_id` bigint unsigned not null, `data` text not null, `read_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `notifications` add index `notifications_notifiable_type_notifiable_id_index`(`notifiable_type`, `notifiable_id`);
alter table `notifications` add primary key `notifications_id_primary`(`id`);
create table `quiz_response` (`id` bigint unsigned not null auto_increment primary key, `question_id` bigint unsigned not null, `student_id` bigint unsigned not null, `answer_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `quiz_response` add constraint `quiz_response_question_id_foreign` foreign key (`question_id`) references `quiz_questions` (`id`) on delete cascade;
alter table `quiz_response` add constraint `quiz_response_student_id_foreign` foreign key (`student_id`) references `users` (`id`) on delete cascade;
alter table `quiz_response` add constraint `quiz_response_answer_id_foreign` foreign key (`answer_id`) references `quiz_answers` (`id`) on delete cascade;
alter table `quiz_response` add index `quiz_response_question_id_index`(`question_id`);
alter table `quiz_response` add index `quiz_response_student_id_index`(`student_id`);
alter table `quiz_response` add index `quiz_response_answer_id_index`(`answer_id`);
create table `sections` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(125) not null, `course_id` bigint unsigned not null, `status` tinyint(1) not null default '1', `description` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `sections` add constraint `sections_course_id_foreign` foreign key (`course_id`) references `courses` (`id`) on delete cascade;
create table `lessons` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(125) not null, `description` varchar(125) null, `status` tinyint(1) not null default '1', `content` text null, `section_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `lessons` add constraint `lessons_section_id_foreign` foreign key (`section_id`) references `sections` (`id`) on delete cascade;
create table `dashboard_tiles` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(125) not null, `data` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `lesson_files` (`id` bigint unsigned not null auto_increment primary key, `path` varchar(125) not null, `file_name` varchar(125) not null, `session_id` varchar(125) not null, `lesson_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `lesson_files` add constraint `lesson_files_lesson_id_foreign` foreign key (`lesson_id`) references `lessons` (`id`) on delete cascade;
create table `kcs` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(125) not null, `description` varchar(125) not null, `course_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `kcs` add constraint `kcs_course_id_foreign` foreign key (`course_id`) references `courses` (`id`) on delete cascade;
create table `kc_lessons` (`kc_id` bigint unsigned null, `lesson_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `kc_lessons` add constraint `kc_lessons_kc_id_foreign` foreign key (`kc_id`) references `kcs` (`id`) on delete cascade;
alter table `kc_lessons` add constraint `kc_lessons_lesson_id_foreign` foreign key (`lesson_id`) references `lessons` (`id`) on delete cascade;
alter table `kc_lessons` add primary key `kc_lessons_kc_id_lesson_id_primary`(`kc_id`, `lesson_id`);
alter table `kc_lessons` add index `kc_lessons_kc_id_index`(`kc_id`);
alter table `kc_lessons` add index `kc_lessons_lesson_id_index`(`lesson_id`);
create table `kc_questions` (`kc_id` bigint unsigned null, `question_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `kc_questions` add constraint `kc_questions_kc_id_foreign` foreign key (`kc_id`) references `kcs` (`id`) on delete cascade;
alter table `kc_questions` add constraint `kc_questions_question_id_foreign` foreign key (`question_id`) references `quiz_questions` (`id`) on delete cascade;
alter table `kc_questions` add primary key `kc_questions_kc_id_question_id_primary`(`kc_id`, `question_id`);
alter table `kc_questions` add index `kc_questions_kc_id_index`(`kc_id`);
alter table `kc_questions` add index `kc_questions_question_id_index`(`question_id`);
